'''
AddFriend Function
'''

import mysql.connector
'from mysql.connector import Error'
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    passwd="Tennis007))&",
    database="run_circle",
    auth_plugin= 'mysql_native_password'
)
mycursor = mydb.cursor()

mycursor.execute("select * from friend_connections")
myresult = mycursor.fetchall() #this actually selects the data and displays it

for row in myresult:
    print(row)



def addFriend (db_connector, list_of_args):

    '''
    order of arguments:
    -

    - profile_profile_id_param int
    - profile_profile_id1_param int
    '''

    cursor = db_connector.cursor()
    arg_tup = tuple(list_of_args)

    try:
        cursor.callproc("addFriend", arg_tup)
        db_connector.commit()
        cursor.close()
    except mysql.connector.Error as err:
        print("Boston, we have a problem {}".format(err))

    cursor.close()

def main():
    mycursor.execute("select * from friend_connections")

    main()
