import mysql.connector
from mysql.connector import MySQLConnection, Error


mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    passwd="Tennis007))&",
    database="run_circle"
)


def createCircle(yourHandle, circleName, location):
    mycursor = mydb.cursor()

# this calls the stored proc to SQL and inserts the data given.
    try:
        result_args = mycursor.callproc('createCircle', (yourHandle,circleName, location))
        print(result_args)

# throws an error if there is one
    except Error as e:
        print("Oops, looks like there's a problem: {}".format(e))

    finally:
        mycursor.close()

# main function to call the addfriend function and commits the result.
if __name__ == '__main__':
    createCircle('fruitforall','fruityrunners','Chicago')
    mydb.commit()



